module(
    name = "rules_lean",
    version = "0.0.0",
    compatibility_level = 1,
)

bazel_dep(name = "platforms", version = "1.0.0")

bazel_dep(name = "buildifier_prebuilt", version = "8.2.1", dev_dependency = True)

lean = use_extension("//lean:extensions.bzl", "lean")
lean.toolchain(toolchain_file = "//:lean-toolchain")
lean.mathlib(
    modules = [
        "Mathlib.Data.Finsupp.Basic",
        "Mathlib.Data.Nat.Basic",
        "Mathlib.Data.Nat.Prime.Infinite",
        "Mathlib.Logic.Function.Basic",
    ],
)
use_repo(lean, "lean_imports", "lean_toolchains", "mathlib")

register_toolchains("@lean_toolchains//:all")
