import Isa.Opcodes
import Rtl.Types

/-!
Decode a 32-bit instruction word against the generated opcode table.
`Isa.Opcodes` is generated by a `genrule`, so this module is compiled from a
generated source.
-/

namespace Isa

/-- A decoded instruction. -/
structure Instr where
  name : String
  rd : Nat
  rs1 : Nat
  imm : Nat
  deriving Repr, DecidableEq

/-- Decode one instruction word. `none` when no opcode matches. -/
def decode (word : Nat) : Option Instr :=
  let opcode := word &&& 0x7f
  let row? := opcodes.find? (fun row => row.opcode == opcode)
  match row? with
  | none => none
  | some row =>
    let rd := (word >>> 7) &&& 0x1f
    let rs1 := (word >>> 15) &&& 0x1f
    let imm := (word >>> 20) &&& 0xfff
    if row.hasRd && rd == 0 then none
    else some ⟨row.name, rd, rs1, imm⟩

end Isa
